### PR TITLE
Add standalone recipe for single node installation

### PR DESCRIPTION
**Pull request by jgillis01**
Remove gem conflicts

### CODE REVIEW

**Comment by yportnoy** [comment]
jenkins retest please

**Comment by yportnoy** [comment]
test please

**Comment by yportnoy** [comment]
please retest

**Comment by yportnoy** [comment]
Could you re base and version bump this @jgillis01

**Comment by jgillis01** [comment]
It looks like gem installation of nokogiri is failing. It probably needs the build-essentials package to be installed.

**Comment by jgillis01** [comment]
now running into apt index issues. Adding that to the run list.

**Comment by jgillis01** [comment]
Jenkins, retest this please.

**Pull request merged**
